function res_LL = fun_LL_per_data(model_inputs,prms_info,y_idx,times_vec,inData,exp_type)
LL_vec = zeros(1,size(inData,1));
parfor data_idx = 1:size(inData,1)
    LL_vec(data_idx) = fun_LL(model_inputs(data_idx,:),...
                                prms_info,...
                                      y_idx,...
                                          times_vec, ...
                                              inData(data_idx,:),...
                                                  exp_type);
end
res_LL = sum(LL_vec);
