function fun_print_parameter_est_bin(prms_est)
% PARAMETERS
% k_1on [01]; k_1off [02]; k_2 [03];   k_3on [04];  k_3off [05];
% k_4on [06]; k_4off [07]; k_5on [08]; k_5off [09];
% k_6on [10]; k_6off [11]; k_7on [12]; k_7off [13];
% k_8on [14]; k_8off [15]; sigma [16];
% fprintf('Parameters Estimated:\n');
fprintf(['k_1on: %d,    k_1off: %d\n', ...
    'k_cat: %d, \n',...  
    'k_3on: %d,    k_3off: %d \n',...  
    'k_4on: %d,    k_4off: %d \n',...   
    'k_5on: %d,    k_5off: %d \n',...  
    'k_6on: %d,    k_6off: %d \n',...  
    'k_7on: %d,    k_7off: %d \n',...  
    'k_8on: %d,    k_8off: %d \n',...
    'sigma: %d \n'],prms_est);
